//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBApiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arızalar
    {
        public int ArızaNo { get; set; }
        public int Kat1 { get; set; }
        public int Kat2 { get; set; }
        public string ArızaBaslik { get; set; }
        public string ArızaNotu { get; set; }
        public System.DateTime ArızaTarihi { get; set; }
        public string ArızaYeri { get; set; }
        public string ArızaDurumu { get; set; }
        public string CozumAciklama { get; set; }
        public Nullable<int> CozumEkibi { get; set; }
        public Nullable<System.DateTime> CozumTarihi { get; set; }
        public int Olusturan { get; set; }
    
        public virtual Kategori_1 Kategori_1 { get; set; }
        public virtual Kategori_2 Kategori_2 { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Arızalar Arızalar1 { get; set; }
        public virtual Arızalar Arızalar2 { get; set; }
        public virtual Ekipler Ekipler { get; set; }
    }
}
