//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBApiDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbATUEntities : DbContext
    {
        public dbATUEntities()
            : base("name=dbATUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arızalar> Arızalar { get; set; }
        public virtual DbSet<Ekipler> Ekipler { get; set; }
        public virtual DbSet<Kategori_1> Kategori_1 { get; set; }
        public virtual DbSet<Kategori_2> Kategori_2 { get; set; }
        public virtual DbSet<KullaniciGruplari> KullaniciGruplari { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Tokens> Tokens { get; set; }
        public virtual DbSet<LogMetaData> LogMetaData { get; set; }
    }
}
