//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.TokenList = new HashSet<TokenList>();
        }
    
        public int KullaniciNo { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public int PersonelNo { get; set; }
        public int KullaniciGrubu { get; set; }
    
        public virtual KullaniciGruplari KullaniciGruplari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TokenList> TokenList { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
